version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5433:5432'
    volumes:
      - polls_pg_data:/bitnami/postgresql
    env_file:
      - .env

volumes:
  polls_pg_data: